version: '2'

networks:
  microservice_transactions:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.22/16
          gateway: 172.18.0.1

services:
  mysql-database:
    image: mysql:5.7
    container_name: mysql-database
    command: mysqld --character-set-server=utf8mb4
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    networks:
      - microservice_transactions
    ports:
      - "3306:3306"

  eureka-server:
    container_name: eureka-server
    build:
      context: ./eureka-server
      dockerfile: dockerfile
    image: eureka-server:latest
    networks:
      - microservice_transactions
    ports:
      - "8761:8761"

  order-service:
    container_name: order-service
    build:
      context: ./order-service
      dockerfile: dockerfile
    image: order-service:latest
    networks:
      - microservice_transactions
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server

  customer-service:
    container_name: customer-service
    build:
      context: ./customer-service
      dockerfile: dockerfile
    image: customer-service:latest
    networks:
      - microservice_transactions
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server

  storage-service:
    container_name: storage-service
    build:
      context: ./storage-service
      dockerfile: dockerfile
    image: storage-service:latest
    networks:
      - microservice_transactions
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
