#!/bin/bash
customerId=1
productId=2
curl -X 'POST' "http://localhost:8080/twoPhaseLock/order/for/$customerId/product/$productId" -o res1 &
curl -X 'POST' "http://localhost:8080/twoPhaseLock/order/for/$customerId/product/$productId" -o res2 &
